version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.7
    commands:
      - pip install cfn-lint
  build:
    commands:
      - cfn-lint -t sam-app/template.yaml
      - cd sam-app/
      - sam build
  post_build:
    commands:
      - sam package --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged-template.yaml
artifacts:
  files:
    - sam-app/packaged-template.yaml
